### ISSUE TITLE
subtitles stopped working since the latest update 

### ISSUE THREAD

**Issue by freakynuell** [flixclusiveorg/Flixclusive#122]
### Steps to reproduce

Selecting subtitle on in the settings dont work for movies that initially has subtitle prior to recent update 

### Expected behavior

Subtitles should work

### Actual behavior

Subtitles dont work

### App version

2.0.1

### Android version

android 7

### Device

Smart Tv

### Acknowledgements

- [X] I am ***fully confident*** that this issue is related solely to the app and not to any provider.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[pre-release version](https://github.com/flixclusiveorg/Flixclusive/releases/tag/pre-release)**.

**Comment by rhenwinch** [comment]
Known issue from discord. Thanks for jotting it down here so I can personally track it.

**Comment by rhenwinch** [comment]
re-open if issue still persists
