### ISSUE TITLE
Subtitles Changing on its own

### ISSUE THREAD

**Issue by Code-Xeno** [flixclusiveorg/Flixclusive#123]
### Steps to reproduce

![Screenshot_2024-09-28-01-41-24-90_e8ccd80afe35f7798e3674be308ad800](https://github.com/user-attachments/assets/9330bf37-c363-4449-b463-61a5daa3a0a7)
![Screenshot_2024-09-28-01-51-44-44_e8ccd80afe35f7798e3674be308ad800](https://github.com/user-attachments/assets/a70d9ad9-cfa8-4ba4-bb23-8a43edc1b04d)

### Expected behavior

I would like the subtitles to stay, the one I selected

### Actual behavior

I installed the app for the first time and I decided to watch blade runner 2049 but whenever I close my phone or exit the app and then re-open the app, the subtitles change to the default eng subtitles but the subtitles was not working which was why I changed it to 'Eng 2' but sometime it even changed to the default subtitle without my phone closing or exiting the app. Pls look into this

### App version

2.0.1

### Android version

Android 14

### Device

OnePlus Nord N30 5G

### Acknowledgements

- [X] I am ***fully confident*** that this issue is related solely to the app and not to any provider.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[pre-release version](https://github.com/flixclusiveorg/Flixclusive/releases/tag/pre-release)**.

**Comment by rhenwinch** [comment]
Could be same with #122

This has been patched for the next updates.
