### ISSUE TITLE
Can't Use Super Stream

### ISSUE THREAD

**Issue by MarshMeadow** [flixclusiveorg/Flixclusive#124]
### Steps to reproduce

i got to use it and dose not work then when I configure it for some reason it wants me to sign in why is this??

### Expected behavior

just to use and be done not want a sign in??

### Actual behavior

...

### Crash logs (or stack trace)

...

### App version

Latest

### Android version

14

### Device

Sam s23 fe

### Other details

![Screenshot_20240930-173022_Flixclusive](https://github.com/user-attachments/assets/3188d7be-acb2-47bb-8dc0-5a6175d395ee)

### Acknowledgements

- [X] I am ***fully confident*** that this issue is related solely to the app and not to any provider.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[pre-release version](https://github.com/flixclusiveorg/Flixclusive/releases/tag/pre-release)**.

**Comment by rhenwinch** [comment]
Apologies. Will be closing this one as it does not concern the app anymore
